# Generated by Django 4.0.5 on 2022-08-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moto', models.TextField()),
                ('short_history', models.TextField()),
                ('church_office', models.IntegerField()),
                ('church_mobile', models.IntegerField()),
                ('detailed_history', models.TextField()),
            ],
        ),
    ]
